# Conclusion
## Main Takeaways of Exploration
Overall, we concluded that SAT scores are not the best metric to predict how students perform in college. Although there is some correlation between high SAT scores and high college GPAs, there is an even stronger indicator when utilizing high school GPAs instead.<br />

In terms of the California SAT Analyses, we determined that the shifts and changes in SAT standards changes (i.e., the adding of sections and increase of maximum score) did not have a substantial effect on the average score per section over the years. Neither did it have an effect on the ratio of the average total score to the maximum possible score for that year. However, it did have varying effects on the average percentage of students who achieved at least an average SAT score—with years from 2005 below scoring have the lowest percentage, 2009 having the highest, and every other year ranking high as well. <br />

With this taken into consideration, we were able to determine that the SATs have biases, as those who are apart of certain socioeconomically disadvantaged counties are less likely to achieve average SAT scores. Specifically, our data showed that students who are not white and impoverished students are at sever disadvantages. Because these demographics do not have an effect on an individual's academic ability, but do have an effect on how high the score on an SAT, we concluded that the SAT is not <i>fair</i> enough to be used as a metric of college performance and readiness, race and household income considered.


## Limitations
One of our more blatant limitations, especially in the later analyses, were the missing values in SAT and demographic data. In Dataset 4, we saw that for some the years, though the amount of schools or counties with missing data was not substantial in comparison to the filled values, it was still a large number. As there was no way for us to fill in or assume the missing data values, this may have affected our project's results in unknown ways. Another limitation was also not being able to find readily accessible demographic datasets prior to 2005—which meant there there was an entire era of the SATs (in terms of standards and scores) that were not able to identify possible bias trends for. Doing this would have allowed for a fuller picture of the story the data conveyed. Lastly, another limitation was only having access to the Princeton96 datasets from Chance. Despite it being a wonderful dataset to work with for the sake of our project, it was collected from students from Princeton—an ivy league with very rigorous testing standards. This may have presented some unknown bias to our results. Moreover, the dataset was last updated in 2013. It would have been nice to have access to a more recent study as well, and create visualizations comparing the two, thus creating a fuller-picture story.

## Future Directions
If we were to take future steps for this project, we would look into the trends and visualizations of more recent school data and data from other types of schools (i.e., not just ivy leagues). We would also do a deeper dive into the gender analysis, as the data we had access to may not have beene extensive enough for us to come to a conclusion. As inspiried by our limitations, we would also look into the SAT trends from before 2005 standard change. Moreover, we think it would be interesting to look at the trends from after the 2016 standard change, in addition the trends from the pandemic (sinnce standardized testing was not required for admission for many schools).

