--- 
title: "Standardized Testing"
author: "Haolong Liu, Imani Oluwafumilayo Maliti"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The SAT is a standardized test used by colleges and universities in the United States to assess the academic readiness of applicants and possibly grant them acceptance to their institution. The test is allegedly designed to measure a student's critical thinking, problem-solving, and analytic skills. Moreover, it is typically taken by high school juniors and seniors. The SAT currently consists of three main sections: Reading, Writing and Language, and Math. Scores on the SAT are used by colleges as part of their admissions process, as students with high SAT scores are expected to perform better throughout their undergraduate matriculation. Nevertheless, with this project, we strive to determine if the SATs are a strong and fair indicator of college readiness and performance. We will use data visualizations to show the relationship between SAT scores and college GPA, and compare its strength to the relationship between college GPAhigh school GPA (another alleged strong indicator of college performance). Furthermore, we introduce other factors to be considered, such as gender, overall GPA and first-year GPA, and the breakdown of SAT scores. This way, we can dive deeper to examine the relationships. Additionally, we will also analyze state-wise SAT scores in United States and delve deeper into the potential demographic biases of the SATs using extensive state-level data for California, a state with one of the biggest populations and biggest education systems in the country.