# Proposal

## Research topic
What are the determinants of high school students’ ability to succeed in college? One may argue that high school GPA is a statistically sound predictor. However, others may say that the Scholastic Aptitude Test (i.e, SAT) is a better one. Nevertheless, the question remains whether or not either are actually accurate of students’ preparedness for and performance in college. In this research project, we seek answers for the following questions: What is the relationship between SAT score and college GPA? Is high school GPA a better predictor for college GPA than SAT scores? Is the SAT even an unbias and consistent-enough measure to predict college performance in the first place? Conducting this research may help students better understand how to viably prepare for their journey in higher education. Also, studying how the SAT’s effect college success (or lack thereof) may also guide us to think deeper about the current admission systems. Examining differences in demographics could aid in taking a closer at the fairness of the admission system in terms of gender diversity. The reason we choose to analyze the SAT only is because it is the most common standardized test in the United States; moreover, focusing on one test increases the consistency of the data.

## Data availability
### Dataset 1: 1000 anonymous students’ SAT and GPA
This dataset was collected by Chance, a quantitative literacy course developed cooperatively by the Chance Team: J. Laurie Snell and Peter Doyle of Dartmouth College, Joan Garfield of the University of Minnesota, Tom Moore of Grinnell College, Bill Peterson of Middlebury College, and Ngambal Shah of Spelman College. The dataset collects 1000 anonymous students’ gender, SAT scores, high-school GPA, and first-year college GPA. The raw data is directly accessible from the following link:<br />
<https://chance.dartmouth.edu/course/Syllabi/Princeton96/ETSValidation.html>

### Dataset 2: Dartmouth Male and Female Students who take Psychology Courses’ SAT and GPA
These two datasets are collected by the same source, Chance. Attributes include SAT verbal, SAT math scores, SAT scores, total GPA, major GPA, and two Psych courses’ GPA. The two datasets represent male students and female students respectively and are collected at the same time. These datasets are small-scaled and are not updated. They are accessible through the following links:<br />
<https://chance.dartmouth.edu/course/Syllabi/Princeton96/Dartmouth.men.html><br />
<https://chance.dartmouth.edu/course/Syllabi/Princeton96/Dartmouth.women.html> <br />
<br />
Including the first dataset with these, we could analyze the extent to which high-school GPAs and SAT scores help students succeed in college. Furthermore, we can identify which one is a more important factor. Since we have students’ genders, we can also compare results between two genders and see whether a significant difference exists or not.

### Dataset 3: 2018 SAT Annual Report
States Average SAT Scores in 2018. This data set is published by College Board, the 2018 SAT Suite of Assessments Annual Report, and it is accessible from <https://reports.collegeboard.org/sat-suite-program-results>. The Attributes include: State: states of united states. Participation: Participation rate of students in each state for SAT exam. Evidence-Based Reading and Writing: State Average of SAT Verbal scores. Math: State Average of SAT Math scores. Total: State Average of total SAT scores. The dataset contains 51 records. It counts District of Columbia as a State.

### Dataset 4: California SAT Reports from 1998 to 2016
Each state in the United States has its own Department of Education that creates reports on SAT scores by district and school. Take California’s report for example. This dataset is collected by the California Department of Education (CDE). CDE receives California public school students’ SAT scores from the College Board, then groups the data by school, district, country, and state to produce California SAT Report. Scores for schools that had fewer than eleven students taking the SAT are not shown on the SAT Report to preserve the anonymity of the students. The report includes geographical information and a breakdown of average SAT scores. Data attributes include school, district, county, number of takers, average reading, writing, math scores, and percent of test takers whose total SAT scores are greater or equal to 1500. With this dataset, we can analyze whether California students are doing better over time. Also, since the datasets cover a longer time period, we could possibly do a time-series analysis on how California’s SAT scores changed over time. Furthermore, a state-wise comparison of SAT scores may also help us understand the fairness of admissions in the United States. The data is accessible through the following link:<br />
<https://data.world/education/california-sat-reports/workspace/intro>

### Dataset 5: KidsData.org California Demographic Data
From KidsData.org, we collected three of their California-specific datasets, all of which were broken down by the same Counties in the California SAT Report data.<br />
The first dataset is Child Population, by County by Race/Ethnicity. The table reports the percentage of children who identify with a list of races in each county from 1995 to 2021. The total options for race breakdown are the following: African American/Black, American Indian/Alaska Native, Asian, Hispanic/Latino, Native Hawaiian/Pacific Islander, White, and Multiracial. The dataset also provides the option to review this data in the format of count as opposed to percentage. The data is accessible through the following link:<br />
<https://www.kidsdata.org/topic/33/child-population-race/table#fmt=144&loc=2,127,347,1763,331,348,336,171,321,345,357,332,324,369,358,362,360,337,327,364,356,217,353,328,354,323,352,320,339,334,365,343,330,367,344,355,366,368,265,349,361,4,273,59,370,326,333,322,341,338,350,342,329,325,359,351,363,340,335&tf=141&ch=7,11,70,10,72,9,73><br />
The second dataset is Child Population, by County by Age Group and Gender. Similarly to the previous dataset, it reports the percentage (or count) of children who identify with a list of age groups and genders in each county from 1995 to 2021. The following are all the options for age groups: Ages 0-2, Ages 3-5, Ages 6-10, Ages 11-13, Ages 14-17, and Total for Ages 0-17. The options for gender are Female and Male. The data is accessible through the following link:<br />
<https://www.kidsdata.org/topic/34/child-population-age-gender/table#fmt=141&loc=2,127,347,1763,331,348,336,171,321,345,357,332,324,369,358,362,360,337,327,364,356,217,353,328,354,323,352,320,339,334,365,343,330,367,344,355,366,368,265,349,361,4,273,59,370,326,333,322,341,338,350,342,329,325,359,351,363,340,335&tf=141&ch=1433,926,927,1434,1435,372,78,77,79><br />
The final dataset is Children in Poverty, by Race/Ethnicity (Regions of 10,000 Residents or More). The table reports the percentage of children who live in poverty in each county from 2005 to 2018. The options for race and ethnicity are consistent with the first dataset. The data is accessible through the following link:<br />
<https://www.kidsdata.org/topic/544/poverty-race-10k/table#fmt=727&loc=2,127,1763,331,348,336,171,321,345,357,332,324,369,358,362,360,337,327,364,356,217,353,328,354,352,320,339,334,365,343,330,367,344,355,366,368,265,349,361,4,273,59,370,326,322,341,338,350,342,329,325,359,351,363,340,335&tf=132&ch=7,11,726,10,72,9,73,1298><br />
With these datasets, we can observe if there are any underlying demographic biases that contribute to higher SAT scores—despite the fact that ethically, we believe these demographics are not determinants of intelligence and thus, academic performance.




